language: ruby
install: bundle install

install: bundle install
script: bundle exec rake

before_script:
- bundle exec rake db:create db:migrate RAILS_ENV=test

rvm:
- 2.1.2

env:
  global:
    - DATABASE_URL=postgres://postgres@localhost/test
